### ISSUE TITLE
Missing dataset

### ISSUE THREAD

**Issue by hminle** [Jeanselme/NeuralFineGray#1]
Hi @Jeanselme 

Thanks for the great work.

In https://github.com/Jeanselme/NeuralFineGray/blob/614f4f340225e0b474c6e3e71c8b1ed69d1f236b/examples/FineGray.R#L18C5-L18C58
it requires data to run. 
But it seems that your repo does not include these data.
Could you please provide it?

Best.

**Comment by Jeanselme** [comment]
Thanks, these files are generated when running: `/examples/process_data.py`

**Comment by hminle** [comment]
Thank you so much, I got it

**Comment by hminle** [comment]
Hi @Jeanselme ,

I tried to run `/examples/process_data.py` but got this error:
<img width="1058" alt="image" src="https://github.com/Jeanselme/NeuralFineGray/assets/16201681/d29e02bf-a344-4279-8b62-ef1fae9ad801">
Do you know what it is?

Thanks

**Comment by Jeanselme** [comment]
Access to the SEER dataset is restricted, you would need to request access and then export the data. 
The other publicly available dataset should work - Let me know if you have any issue with those, I will update the README accordingly !

**Comment by hminle** [comment]
I am trying to generate competing risks data. So I tried another one which is SYNTHETIC_COMPETING, and got this error:
<img width="1040" alt="image" src="https://github.com/Jeanselme/NeuralFineGray/assets/16201681/4389a5a2-682a-428d-bf50-72f3531a77a4">

**Comment by Jeanselme** [comment]
Thanks, you need to create a 'data/' folder - I have just updated the README

**Comment by Jeanselme** [comment]
If you are just interested in the raw data, you can call the function `load_dataset` from `nfg.datasets`

**Comment by hminle** [comment]
Thank @Jeanselme . Just want to add to your README
We should cd to examples and then run process_data.py inside there

**Comment by hminle** [comment]
Hi @Jeanselme ,
in your notebook to analyze results:
![image](https://github.com/Jeanselme/NeuralFineGray/assets/16201681/4c278122-1c5c-4bc9-9b55-573f5706d4e3)
seems that my output does not contain "n="
so I cannot get any results. What does it mean?

**Comment by hminle** [comment]
Here is my output
<img width="640" alt="image" src="https://github.com/Jeanselme/NeuralFineGray/assets/16201681/b36863f8-d6d5-4059-8063-3db6c07adba4">

**Comment by hminle** [comment]
If I comment out those lines and keep running, I get this error for FineGray results
![image](https://github.com/Jeanselme/NeuralFineGray/assets/16201681/d8d59e41-1ffb-4a77-8e75-0f6a386416b4)
Do you know what it means?

**Comment by Jeanselme** [comment]
You are right you need to comment this, I ll update the notebook
What does your finegray.csv look like ?

**Comment by hminle** [comment]
It looks like this
![image](https://github.com/Jeanselme/NeuralFineGray/assets/16201681/8f5c062d-c958-449f-aef4-53687d044190)

**Comment by Jeanselme** [comment]
Thanks, that was the issue, I have just updated the FineFray file, this should solve the problem !

**Comment by hminle** [comment]
Hi @Jeanselme , there is an error in FineGray R script after I pull the latest code
<img width="956" alt="image" src="https://github.com/Jeanselme/NeuralFineGray/assets/16201681/7908d397-26d9-470d-906c-89ee1dd0c88d">
Could you help to check it out?
Thanks

**Comment by hminle** [comment]
The Rscript can still generate results like this:
![image](https://github.com/Jeanselme/NeuralFineGray/assets/16201681/5bfac7a3-1cd9-4ec6-8138-f693a9788dec)
But the analysis notebook got an error if I tried to analyze the FineGray results
![image](https://github.com/Jeanselme/NeuralFineGray/assets/16201681/5aff728f-3263-4aed-863d-8d9effe65962)

**Comment by Jeanselme** [comment]
My mistake, I didn't update the script, let me know if that works

**Comment by hminle** [comment]
Thank @Jeanselme , I can run the FineGray script now. 
But when trying the analysis notebook with FineGray results, I get this error
![image](https://github.com/Jeanselme/NeuralFineGray/assets/16201681/0e057c37-eb76-443d-ad47-30de1f1a950b)

**Comment by Jeanselme** [comment]
This seems to come from the pandas version you use, I have updated the script, let me know if this works

**Comment by hminle** [comment]
Thank Jeanselme
I use `pandas==2.0.3`
I got another error. I use SYNTHETIC_COMPETING dataset
![image](https://github.com/Jeanselme/NeuralFineGray/assets/16201681/e4f9d702-cde9-4491-9efa-9d17ab33e902)

**Comment by hminle** [comment]
This is my coxcs results:
![image](https://github.com/Jeanselme/NeuralFineGray/assets/16201681/dc673ea5-eb3f-4507-8104-181608d19d3b)

**Comment by Jeanselme** [comment]
This is strange, this seems to work beforeOn 31 Oct 2023, at 21:12, Hoang M. Le ***@***.***> wrote:﻿
This is my coxcs results:

**Comment by Jeanselme** [comment]
Thank you for your helpOn 31 Oct 2023, at 21:16, Hoang M. Le ***@***.***> wrote:﻿
Let me delete everything, and try to run from scratch again

**Comment by hminle** [comment]
Thank you so much. I am able to generate the results
![image](https://github.com/Jeanselme/NeuralFineGray/assets/16201681/45ad74e9-0dbd-496a-85e6-a7ad4a0241f4)

**Comment by hminle** [comment]
Yes, I just run 1 epoch to make sure all the code works.
I will re-train with your original settings to get the final results.
Thanks

**Comment by Jeanselme** [comment]
Great ! Thank you for your help and sorry for the few bugs

**Comment by hminle** [comment]
No problem. I also thank you for the great code :)
