### ISSUE TITLE
Possible Bug in Framingham example ipynb

### ISSUE THREAD

**Issue by dhaneshr** [Jeanselme/NeuralFineGray#8]

**Comment by aminKMT** [comment]
# Debug the evaluation section for Brier score estimation.
## DEBUG: Interpolate out_survival to have columns equal to len(times)
 Assume that the original out_survival is computed over 1000 evenly spaced time points between 0 and 1.

` from scipy.interpolate import `interp1d`
  
`all_times = np.linspace(0, 1, out_survival.shape[1]) `
`out_survival_interp = np.zeros((out_survival.shape[0], len(times)))`
